<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-18T19:50:37 IST" name="Suite" finished-at="2024-07-18T19:51:14 IST" duration-ms="37082">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidations.LoginErrorValidation()[pri:0, instance:SelfLearning.tests.ErrorValidations@530712d]" name="LoginErrorValidation" class="SelfLearning.tests.ErrorValidations"/>
      </group> <!-- ErrorHandling -->
      <group name="purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:SelfLearning.tests.SubmitOrderTest@344f4dea]" name="submitOrder" class="SelfLearning.tests.SubmitOrderTest"/>
      </group> <!-- purchase -->
    </groups>
    <test started-at="2024-07-18T19:50:37 IST" name="ErrorValidations" finished-at="2024-07-18T19:51:09 IST" duration-ms="31969">
      <class name="SelfLearning.tests.ErrorValidations">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SelfLearning.tests.ErrorValidations@530712d]" started-at="2024-07-18T19:50:37 IST" name="launchApplication" finished-at="2024-07-18T19:50:48 IST" duration-ms="11415" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:SelfLearning.tests.ErrorValidations@530712d]" started-at="2024-07-18T19:50:48 IST" name="LoginErrorValidation" finished-at="2024-07-18T19:50:48 IST" duration-ms="402" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SelfLearning.tests.ErrorValidations@530712d]" started-at="2024-07-18T19:50:49 IST" name="launchApplication" finished-at="2024-07-18T19:50:55 IST" duration-ms="6306" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:SelfLearning.tests.ErrorValidations@530712d]" started-at="2024-07-18T19:50:55 IST" name="ProductErrorValidation" finished-at="2024-07-18T19:51:09 IST" duration-ms="13792" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
      </class> <!-- SelfLearning.tests.ErrorValidations -->
    </test> <!-- ErrorValidations -->
    <test started-at="2024-07-18T19:50:37 IST" name="SubmitOrderTest" finished-at="2024-07-18T19:51:14 IST" duration-ms="37082">
      <class name="SelfLearning.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SelfLearning.tests.SubmitOrderTest@344f4dea]" started-at="2024-07-18T19:50:37 IST" name="launchApplication" finished-at="2024-07-18T19:50:48 IST" duration-ms="11458" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:SelfLearning.tests.SubmitOrderTest@344f4dea]" started-at="2024-07-18T19:50:48 IST" name="submitOrder" data-provider="getData" finished-at="2024-07-18T19:50:51 IST" duration-ms="2464" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Test@1234, product=ZARA COAT 3, email=mpavithra18@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.ElementClickInterceptedException">
            <message>
              <![CDATA[Element <button class="btn btn-primary" type="button"> is not clickable at point (1096,580) because another element <div class="ng-tns-c4-2 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-success"> obscures it
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [a8920f13-a02c-438f-b5f7-5d0d98a6ccc1, clickElement {id=fdcf0068-a6ad-44a5-89d3-3d4ee8e0a47f}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 128.0, moz:accessibilityChecks: false, moz:buildID: 20240704121409, moz:debuggerAddress: 127.0.0.1:15483, moz:geckodriverVersion: 0.34.0, moz:headless: false, moz:platformVersion: 10.0, moz:processID: 3264, moz:profile: C:\Users\PAVITH~1.MAT\AppDa..., moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://127.0.0.1:15483/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, userAgent: Mozilla/5.0 (Windows NT 10....}
Element: [[FirefoxDriver: firefox on windows (a8920f13-a02c-438f-b5f7-5d0d98a6ccc1)] -> xpath: //button[contains(text(),'Checkout')]]
Session ID: a8920f13-a02c-438f-b5f7-5d0d98a6ccc1]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.ElementClickInterceptedException: Element <button class="btn btn-primary" type="button"> is not clickable at point (1096,580) because another element <div class="ng-tns-c4-2 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-success"> obscures it
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [a8920f13-a02c-438f-b5f7-5d0d98a6ccc1, clickElement {id=fdcf0068-a6ad-44a5-89d3-3d4ee8e0a47f}]
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 128.0, moz:accessibilityChecks: false, moz:buildID: 20240704121409, moz:debuggerAddress: 127.0.0.1:15483, moz:geckodriverVersion: 0.34.0, moz:headless: false, moz:platformVersion: 10.0, moz:processID: 3264, moz:profile: C:\Users\PAVITH~1.MAT\AppDa..., moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://127.0.0.1:15483/devtoo..., se:cdpVersion: 85.0, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, userAgent: Mozilla/5.0 (Windows NT 10....}
Element: [[FirefoxDriver: firefox on windows (a8920f13-a02c-438f-b5f7-5d0d98a6ccc1)] -> xpath: //button[contains(text(),'Checkout')]]
Session ID: a8920f13-a02c-438f-b5f7-5d0d98a6ccc1
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:224)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy18.click(Unknown Source)
at SelfLearning.pageobjects.CartPage.goToCheckOut(CartPage.java:37)
at SelfLearning.tests.SubmitOrderTest.submitOrder(SubmitOrderTest.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.ElementClickInterceptedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SelfLearning.tests.SubmitOrderTest@344f4dea]" started-at="2024-07-18T19:50:51 IST" name="launchApplication" finished-at="2024-07-18T19:50:58 IST" duration-ms="7315" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:SelfLearning.tests.SubmitOrderTest@344f4dea]" started-at="2024-07-18T19:50:58 IST" name="submitOrder" data-provider="getData" finished-at="2024-07-18T19:51:14 IST" duration-ms="15640" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Test@1234, product=ADIDAS ORIGINAL, email=mpavithra18@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method signature="orderHistoryTest()[pri:0, instance:SelfLearning.tests.SubmitOrderTest@344f4dea]" started-at="2024-07-18T19:51:14 IST" name="orderHistoryTest" finished-at="2024-07-18T19:51:14 IST" depends-on-methods="SelfLearning.tests.SubmitOrderTest.submitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SelfLearning.tests.SubmitOrderTest.orderHistoryTest() on instance SelfLearning.tests.SubmitOrderTest@344f4dea depends on not successfully finished methods 
[SelfLearning.tests.SubmitOrderTest.submitOrder() on instance SelfLearning.tests.SubmitOrderTest@344f4dea]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SelfLearning.tests.SubmitOrderTest.orderHistoryTest() on instance SelfLearning.tests.SubmitOrderTest@344f4dea depends on not successfully finished methods 
[SelfLearning.tests.SubmitOrderTest.submitOrder() on instance SelfLearning.tests.SubmitOrderTest@344f4dea]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistoryTest -->
      </class> <!-- SelfLearning.tests.SubmitOrderTest -->
    </test> <!-- SubmitOrderTest -->
  </suite> <!-- Suite -->
</testng-results>
